addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
before_script:
  - npm install -g testcafe
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
jobs:
  include:
    - stage: Test with GroupDocs.Total-for-Java-Spring
      dist: trusty
      language: java
      jdk : oraclejdk8
      script: 
        - git clone https://github.com/groupdocs-total/GroupDocs.Total-for-Java-Spring
        - cd GroupDocs.Total-for-Java-Spring
        - if git ls-remote --exit-code --heads https://github.com/groupdocs-total/GroupDocs.Total-for-Java-Spring $TRAVIS_BRANCH; then echo "testing with Branch"; git checkout $TRAVIS_BRANCH; else echo "testing with  Master"; fi
        - mvn -q clean spring-boot:run &
        - while ! curl -s http://localhost:8080  > /dev/null ; do sleep 2; echo "waiting to back-end..."; ; done
        - cd ..
        - npm install
        - npm test
    - stage: Test with GroupDocs.Total-for-Java-DropWizard
      dist: trusty
      language: java
      jdk : oraclejdk8
      script: 
        - git clone https://github.com/groupdocs-total/GroupDocs.Total-for-Java-DropWizard
        - cd GroupDocs.Total-for-Java-DropWizard
        - if git ls-remote --exit-code --heads https://github.com/groupdocs-total/GroupDocs.Total-for-Java-DropWizard $TRAVIS_BRANCH; then echo "testing with Branch"; git checkout $TRAVIS_BRANCH; else echo "testing with  Master"; fi
        - mvn -q clean compile exec:java &
        - while ! curl -s http://localhost:8080  > /dev/null ; do sleep 2 ; echo "waiting to back-end..."; done
        - cd ..
        - npm install
        - npm test