dist: trusty
language: node_js
node_js: "stable"
services:
  - docker
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - npm install -g testcafe
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - mkdir DocumentSamples
  - mkdir Licenses
  - docker run -d -p 8080:8080 -v `pwd`/DocumentSamples:/home/groupdocs/app/DocumentSamples -v `pwd`/Licenses:/home/groupdocs/app/Licenses groupdocs/total-for-java-spring
  - while ! curl http://localhost:8080 ; do sleep 1 ; done